<?xml version="1.0" encoding="UTF-8"?>\
<record_update table="sys_script_include">\
<sys_script_include action="INSERT_OR_UPDATE">\
<access>public</access>\
<active>true</active>\
<api_name>x_eslintnow.\x</api_name>\
<caller_access/>\
<client_callable>false</client_callable>\
<description/>\
<name>\x</name>\
<script>{\\x|subs|cdata}</script>\
<sys_class_name>sys_script_include</sys_class_name>\
<sys_created_by>admin</sys_created_by>\
<sys_created_on>{../timestamp.txt|cat}</sys_created_on>\
<sys_id>{1:sys_script_include:1:\x|md5}</sys_id>\
<sys_mod_count>0</sys_mod_count>\
<sys_name>\x</sys_name>\
<sys_package display_value="ESLintNow" source="x_eslintnow">{1:sys_app:1:ESLintNow|md5}</sys_package>\
<sys_policy/>\
<sys_scope display_value="ESLintNow">{1:sys_app:1:ESLintNow|md5}</sys_scope>\
<sys_update_name>sys_script_include_{1:sys_script_include:1:\x|md5}</sys_update_name>\
<sys_updated_by>admin</sys_updated_by>\
<sys_updated_on>{../timestamp.txt|cat}</sys_updated_on>\
</sys_script_include>\
</record_update>
