<sys_update_xml action="INSERT_OR_UPDATE">
<action>INSERT_OR_UPDATE</action>
<application display_value="ESLintNow">{1:sys_app:1:ESLintNow|md5}</application>
<category>customer</category>
<comments/>
<name>\x_{1:\x:1:\\x|md5}</name>
<payload>{\\\\x|subs|cdata}</payload>
<payload_hash>{\\\\x|subs|payhash}</payload_hash>
<remote_update_set display_value="ESLintNow {../timestamp.txt|cat}">{1:sys_remote_update_set:1:ESLintNow:\\\\l../timestamp.txt\\\\pcat\\\\r|subs|eval|md5}</remote_update_set>
<replace_on_upgrade>false</replace_on_upgrade>
<sys_created_by>admin</sys_created_by>
<sys_created_on>{../timestamp.txt|cat}</sys_created_on>
<sys_id>{1:sys_update_xml:1:\\\\x|subs|md5}</sys_id>
<sys_mod_count>0</sys_mod_count>
<sys_recorded_at>{../timestamp.txt|cat|hexstamp}0000001</sys_recorded_at>
<sys_updated_by>admin</sys_updated_by>
<sys_updated_on>{../timestamp.txt|cat}</sys_updated_on>
<table/>
<target_name>\\x</target_name>
<type>{tables/\x.txt|cat}</type>
<update_domain>global</update_domain>
<update_guid>{1:sys_update_xml.update_guid:1:\\\\x|subs|md5}</update_guid>
<update_guid_history>{1:sys_update_xml.update_guid:1:\\\\x|subs|md5}:{\\\\x|subs|payhash}</update_guid_history>
<update_set display_value=""/>
<view/>
</sys_update_xml>
